[package]
name = "mandelbrot_colors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
image = "0.25.1"
crossbeam = "0.8"
rayon ="1.7.0"
rand = "0.8.5"